<?php

declare(strict_types=1);

require __DIR__ . '/StructureTest.php';
require dirname(__DIR__) . '/src/Version.php';
require dirname(__DIR__) . '/src/Platform/UserDirectoryLayout.php';
require dirname(__DIR__) . '/src/Cli/ExitCode.php';
require dirname(__DIR__) . '/src/Cli/UsageException.php';
require dirname(__DIR__) . '/src/Cli/UnavailableException.php';
require dirname(__DIR__) . '/src/Cli/ConfigurationException.php';
require dirname(__DIR__) . '/src/Project/ProjectProfile.php';
require dirname(__DIR__) . '/src/Project/ProfileDetector.php';
require dirname(__DIR__) . '/src/Project/DiscoveryResult.php';
require dirname(__DIR__) . '/src/Project/RuntimeDataPaths.php';
require dirname(__DIR__) . '/src/Project/ProjectDiscovery.php';
require dirname(__DIR__) . '/src/Project/CoverageLedger.php';
require dirname(__DIR__) . '/src/Project/CoveragePlanner.php';
require dirname(__DIR__) . '/src/Project/SourceTreeSnapshot.php';
require dirname(__DIR__) . '/src/Project/WorkspaceCacheKey.php';
require dirname(__DIR__) . '/src/Project/ProjectWorkspace.php';
require dirname(__DIR__) . '/src/Project/ProjectMirror.php';
require dirname(__DIR__) . '/src/Project/DistributionPublisher.php';
require dirname(__DIR__) . '/src/Project/RuntimeResourceManifest.php';
require dirname(__DIR__) . '/src/Project/RuntimeResourcePlanner.php';
require dirname(__DIR__) . '/src/Compatibility/VersionRange.php';
require dirname(__DIR__) . '/src/Compatibility/CompatibilityRule.php';
require dirname(__DIR__) . '/src/Compatibility/BoundedTextRule.php';
require dirname(__DIR__) . '/src/Compatibility/RuleEngine.php';
require dirname(__DIR__) . '/src/Compatibility/WebmanWorkermanRules.php';
require dirname(__DIR__) . '/src/Compatibility/GeneratedProjectAdapter.php';
require dirname(__DIR__) . '/src/Compatibility/PluginSourceCompletion.php';
require __DIR__ . '/PluginSourceCompletionTest.php';
require dirname(__DIR__) . '/src/Compatibility/MonologWebProcessorRule.php';
require dirname(__DIR__) . '/src/Compatibility/NativeIntlPolyfillRule.php';
require dirname(__DIR__) . '/src/Compatibility/SaiAdminProfileOverlay.php';
require dirname(__DIR__) . '/src/Compatibility/UpstreamGeneratorBoundary.php';
require dirname(__DIR__) . '/src/Compatibility/UpstreamGeneratorArchive.php';
require dirname(__DIR__) . '/src/Cli/Application.php';
require __DIR__ . '/GlobalLauncherTest.php';
require __DIR__ . '/InstallerContractTest.php';
require __DIR__ . '/StagePipelineIntegrationTest.php';
require dirname(__DIR__) . '/src/Toolchain/LockValidator.php';
require dirname(__DIR__) . '/src/Toolchain/HostComponentSelector.php';
require dirname(__DIR__) . '/src/Toolchain/ToolchainLocator.php';
require dirname(__DIR__) . '/src/Toolchain/Downloader.php';
require dirname(__DIR__) . '/src/Toolchain/ToolchainPreparer.php';
require dirname(__DIR__) . '/src/Toolchain/ToolchainRepairer.php';
require __DIR__ . '/ToolchainRepairerTest.php';
require dirname(__DIR__) . '/src/Update/TrustedKeyStore.php';
require dirname(__DIR__) . '/src/Update/UpdateManifest.php';
require dirname(__DIR__) . '/src/Update/SignedManifestVerifier.php';
require dirname(__DIR__) . '/src/Update/VerifiedDownloader.php';
require dirname(__DIR__) . '/src/Update/PackageExtractor.php';
require dirname(__DIR__) . '/src/Update/ZipPackageExtractor.php';
require dirname(__DIR__) . '/src/Update/CliSelfChecker.php';
require dirname(__DIR__) . '/src/Update/NativeCliSelfChecker.php';
require dirname(__DIR__) . '/src/Update/CliVersionStore.php';
require dirname(__DIR__) . '/src/Update/SelfUpdater.php';
require dirname(__DIR__) . '/src/Update/UpdateManager.php';
require __DIR__ . '/UpdateSecurityTest.php';
require __DIR__ . '/SelfUpdaterTest.php';
require __DIR__ . '/ToolchainUpdateTest.php';
require dirname(__DIR__) . '/src/Doctor/SystemProbe.php';
require dirname(__DIR__) . '/src/Doctor/DoctorReport.php';
require dirname(__DIR__) . '/src/Doctor/Doctor.php';
require __DIR__ . '/DoctorTest.php';
require __DIR__ . '/ProfileDetectorTest.php';
require __DIR__ . '/ProjectDiscoveryTest.php';
require __DIR__ . '/CoveragePlannerTest.php';
require dirname(__DIR__) . '/src/Project/CompilerCoverageAudit.php';
require dirname(__DIR__) . '/src/Project/GeneratedProjectCoveragePlanner.php';
require __DIR__ . '/CompilerCoverageAuditTest.php';
require __DIR__ . '/GeneratedProjectCoveragePlannerTest.php';
require dirname(__DIR__) . '/src/Project/DistributionLeakScanner.php';
require __DIR__ . '/DistributionLeakScannerTest.php';
require dirname(__DIR__) . '/src/Project/RuntimeResourcePackager.php';
require __DIR__ . '/RuntimeResourcePackagerTest.php';
require dirname(__DIR__) . '/src/Project/RuntimeLauncherWriter.php';
require __DIR__ . '/RuntimeLauncherWriterTest.php';
require dirname(__DIR__) . '/src/Project/DistributionManifestWriter.php';
require dirname(__DIR__) . '/src/Project/DistributionVerifier.php';
require dirname(__DIR__) . '/src/Project/DistributionAssembler.php';
require dirname(__DIR__) . '/src/Project/ProjectBuilder.php';
require __DIR__ . '/DistributionManifestVerifierTest.php';
require __DIR__ . '/DistributionAssemblerTest.php';
require __DIR__ . '/ProjectBuilderTest.php';
require __DIR__ . '/ProjectWorkspaceTest.php';
require __DIR__ . '/ProjectMirrorTest.php';
require __DIR__ . '/DistributionPublisherTest.php';
require __DIR__ . '/RuntimeResourcePlannerTest.php';
require __DIR__ . '/CompatibilityRuleTest.php';
require __DIR__ . '/WebmanWorkermanRulesTest.php';
require __DIR__ . '/GeneratedProjectAdapterTest.php';
require __DIR__ . '/MonologWebProcessorRuleTest.php';
require __DIR__ . '/NativeIntlPolyfillRuleTest.php';
require __DIR__ . '/SaiAdminProfileOverlayTest.php';
require __DIR__ . '/UpstreamGeneratorBoundaryTest.php';
require __DIR__ . '/UpstreamGeneratorArchiveTest.php';
require __DIR__ . '/ToolchainLockTest.php';
require __DIR__ . '/TypePhpPatchManifestTest.php';
require __DIR__ . '/UnifiedPatchApplierTest.php';
require dirname(__DIR__) . '/src/Toolchain/FullStaticProjectOverlay.php';
require __DIR__ . '/FullStaticProjectOverlayTest.php';
require dirname(__DIR__) . '/src/Toolchain/TypePhpPatchManifestFingerprint.php';
require __DIR__ . '/TypePhpPatchManifestFingerprintTest.php';
require dirname(__DIR__) . '/src/Toolchain/TypePhpProjectCompiler.php';
require dirname(__DIR__) . '/src/Toolchain/StaticSdkFingerprint.php';
require dirname(__DIR__) . '/src/Toolchain/PreparedToolchain.php';
require dirname(__DIR__) . '/src/Toolchain/TypePhpPatchSourceVerifier.php';
require __DIR__ . '/TypePhpProjectCompilerTest.php';
require __DIR__ . '/PreparedToolchainTest.php';
require __DIR__ . '/TypePhpPatchSourceVerifierTest.php';
require __DIR__ . '/ReproducibilityInputTest.php';
require __DIR__ . '/WindowsReplayContractTest.php';
require dirname(__DIR__) . '/src/Toolchain/ElfStaticVerifier.php';
require __DIR__ . '/ElfStaticVerifierTest.php';

try {
    $root = dirname(__DIR__);
    (new StructureTest($root))->run();
    (new GlobalLauncherTest())->run($root);
    (new InstallerContractTest())->run($root);
    (new StagePipelineIntegrationTest())->run($root);
    (new ToolchainRepairerTest())->run();
    (new UpdateSecurityTest())->run();
    (new SelfUpdaterTest())->run($root);
    (new ToolchainUpdateTest())->run($root);
    (new DoctorTest())->run($root);
    (new ProfileDetectorTest())->run();
    (new ProjectDiscoveryTest())->run();
    (new PluginSourceCompletionTest())->run($root);
    (new CoveragePlannerTest())->run();
    (new CompilerCoverageAuditTest())->run();
    (new GeneratedProjectCoveragePlannerTest())->run();
    (new DistributionLeakScannerTest())->run();
    (new RuntimeResourcePackagerTest())->run();
    (new RuntimeLauncherWriterTest())->run();
    (new DistributionManifestVerifierTest())->run();
    (new DistributionAssemblerTest())->run();
    (new ProjectBuilderTest())->run($root);
    (new ProjectWorkspaceTest())->run();
    (new ProjectMirrorTest())->run();
    (new DistributionPublisherTest())->run();
    (new RuntimeResourcePlannerTest())->run();
    (new CompatibilityRuleTest())->run();
    (new WebmanWorkermanRulesTest())->run();
    (new GeneratedProjectAdapterTest())->run();
    (new MonologWebProcessorRuleTest())->run();
    (new NativeIntlPolyfillRuleTest())->run();
    (new SaiAdminProfileOverlayTest())->run();
    (new UpstreamGeneratorBoundaryTest())->run($root);
    (new UpstreamGeneratorArchiveTest())->run($root);
    (new ToolchainLockTest())->run($root);
    (new TypePhpPatchManifestTest())->run($root);
    (new UnifiedPatchApplierTest())->run();
    (new FullStaticProjectOverlayTest())->run();
    (new TypePhpPatchManifestFingerprintTest())->run($root);
    (new TypePhpProjectCompilerTest())->run();
    (new PreparedToolchainTest())->run();
    (new TypePhpPatchSourceVerifierTest())->run();
    (new ReproducibilityInputTest())->run($root);
    (new WindowsReplayContractTest())->run($root);
    (new ElfStaticVerifierTest())->run();
    fwrite(STDOUT, "[PASS] repository structure is independent and self-contained\n");
    fwrite(STDOUT, "[PASS] global launcher uses the private user layout without a project plugin\n");
    fwrite(STDOUT, "[PASS] installers are user-private, digest-locked, and package-manager-free\n");
    fwrite(STDOUT, "[PASS] CLI stages emit stable exits, logs, and diagnostic bundles\n");
    fwrite(STDOUT, "[PASS] doctor repair promotes only verified toolchain generations\n");
    fwrite(STDOUT, "[PASS] update manifests and downloads fail closed on tampering or interruption\n");
    fwrite(STDOUT, "[PASS] CLI updates self-check, activate atomically, reject unsafe ZIPs, and roll back\n");
    fwrite(STDOUT, "[PASS] toolchain updates verify signed locks, preserve failures, and roll back\n");
    fwrite(STDOUT, "[PASS] doctor is read-only and detects healthy, missing, and corrupt inputs\n");
    fwrite(STDOUT, "[PASS] project profiles combine Composer locks and structure and fail closed on conflicts\n");
    fwrite(STDOUT, "[PASS] project discovery finds core and plugin PHP and classifies runtime resources\n");
    fwrite(STDOUT, "[PASS] newly discovered plugin business PHP enters compiler sources without widening ignores\n");
    fwrite(STDOUT, "[PASS] coverage ledger closes every file with digests, policies, and four legal statuses\n");
    fwrite(STDOUT, "[PASS] compiler inputs reject omitted or ignored business PHP and missing AOT replacements\n");
    fwrite(STDOUT, "[PASS] generated project coverage closes mapped sources and rejects compiler omissions or shadow drift\n");
    fwrite(STDOUT, "[PASS] project workspace caching and cleanup preserve the source tree digest\n");
    fwrite(STDOUT, "[PASS] isolated project mirror preserves sources and omits private runtime data\n");
    fwrite(STDOUT, "[PASS] verified distributions publish with rollback on replacement failure\n");
    fwrite(STDOUT, "[PASS] staged project builds preserve source and prior distribution on early failure\n");
    fwrite(STDOUT, "[PASS] runtime resources record files and writable directories and reject omissions\n");
    fwrite(STDOUT, "[PASS] bounded compatibility rules generate deterministic shadows and fail on drift\n");
    fwrite(STDOUT, "[PASS] sampled Webman and Workerman dependency rules reject missing, duplicate, and drifted inputs\n");
    fwrite(STDOUT, "[PASS] generated Webman adaptations guard shadow and install-only source structure\n");
    fwrite(STDOUT, "[PASS] Monolog WebProcessor adaptation is versioned, exact-once and digest-locked\n");
    fwrite(STDOUT, "[PASS] native intl polyfill adaptation preserves missing functions and rejects drift\n");
    fwrite(STDOUT, "[PASS] SaiAdmin Carbon profile overlay is bounded and fails on source drift\n");
    fwrite(STDOUT, "[PASS] pinned upstream generator output is audited for source and shadow integrity\n");
    fwrite(STDOUT, "[PASS] pinned upstream generator archive installs privately and rejects drift\n");
    fwrite(STDOUT, "[PASS] toolchain lock schema and digest guards are valid\n");
    fwrite(STDOUT, "[PASS] TypePHP patch manifest and patch set are guarded\n");
    fwrite(STDOUT, "[PASS] unified patches apply exactly and fail closed on drift\n");
    fwrite(STDOUT, "[PASS] full-static TypePHP project overlay guards the generator shape and sysroot\n");
    fwrite(STDOUT, "[PASS] TypePHP patch manifest fingerprint ignores rule order and rejects drift\n");
    fwrite(STDOUT, "[PASS] TypePHP project executor uses explicit tools and rejects failed or dynamic ELF output\n");
    fwrite(STDOUT, "[PASS] prepared toolchains reject host, lock, path and SDK drift\n");
    fwrite(STDOUT, "[PASS] prepared compiler source matches every locked TypePHP patch digest\n");
    fwrite(STDOUT, "[PASS] normalized reproducibility input is deterministic\n");
    fwrite(STDOUT, "[PASS] Windows replay remains CLI-only and lock-driven\n");
    fwrite(STDOUT, "[PASS] ELF static verifier rejects dynamic and unloadable artifacts\n");
    exit(0);
} catch (Throwable $throwable) {
    fwrite(STDERR, '[FAIL] ' . $throwable->getMessage() . PHP_EOL);
    exit(1);
}
