<?php

declare(strict_types=1);

require __DIR__ . '/StructureTest.php';
require dirname(__DIR__) . '/src/Version.php';
require dirname(__DIR__) . '/src/Platform/UserDirectoryLayout.php';
require dirname(__DIR__) . '/src/Cli/ExitCode.php';
require dirname(__DIR__) . '/src/Cli/UsageException.php';
require dirname(__DIR__) . '/src/Cli/UnavailableException.php';
require dirname(__DIR__) . '/src/Cli/ConfigurationException.php';
require dirname(__DIR__) . '/src/Project/ProjectProfile.php';
require dirname(__DIR__) . '/src/Project/ProfileDetector.php';
require dirname(__DIR__) . '/src/Cli/Application.php';
require __DIR__ . '/GlobalLauncherTest.php';
require __DIR__ . '/InstallerContractTest.php';
require __DIR__ . '/StagePipelineIntegrationTest.php';
require dirname(__DIR__) . '/src/Toolchain/LockValidator.php';
require dirname(__DIR__) . '/src/Toolchain/HostComponentSelector.php';
require dirname(__DIR__) . '/src/Toolchain/ToolchainLocator.php';
require dirname(__DIR__) . '/src/Toolchain/Downloader.php';
require dirname(__DIR__) . '/src/Toolchain/ToolchainRepairer.php';
require __DIR__ . '/ToolchainRepairerTest.php';
require dirname(__DIR__) . '/src/Update/TrustedKeyStore.php';
require dirname(__DIR__) . '/src/Update/UpdateManifest.php';
require dirname(__DIR__) . '/src/Update/SignedManifestVerifier.php';
require dirname(__DIR__) . '/src/Update/VerifiedDownloader.php';
require dirname(__DIR__) . '/src/Update/PackageExtractor.php';
require dirname(__DIR__) . '/src/Update/ZipPackageExtractor.php';
require dirname(__DIR__) . '/src/Update/CliSelfChecker.php';
require dirname(__DIR__) . '/src/Update/NativeCliSelfChecker.php';
require dirname(__DIR__) . '/src/Update/CliVersionStore.php';
require dirname(__DIR__) . '/src/Update/SelfUpdater.php';
require dirname(__DIR__) . '/src/Update/UpdateManager.php';
require __DIR__ . '/UpdateSecurityTest.php';
require __DIR__ . '/SelfUpdaterTest.php';
require __DIR__ . '/ToolchainUpdateTest.php';
require dirname(__DIR__) . '/src/Doctor/SystemProbe.php';
require dirname(__DIR__) . '/src/Doctor/DoctorReport.php';
require dirname(__DIR__) . '/src/Doctor/Doctor.php';
require __DIR__ . '/DoctorTest.php';
require __DIR__ . '/ProfileDetectorTest.php';
require __DIR__ . '/ToolchainLockTest.php';
require __DIR__ . '/TypePhpPatchManifestTest.php';
require __DIR__ . '/UnifiedPatchApplierTest.php';
require __DIR__ . '/ReproducibilityInputTest.php';
require __DIR__ . '/WindowsReplayContractTest.php';
require dirname(__DIR__) . '/src/Toolchain/ElfStaticVerifier.php';
require __DIR__ . '/ElfStaticVerifierTest.php';

try {
    $root = dirname(__DIR__);
    (new StructureTest($root))->run();
    (new GlobalLauncherTest())->run($root);
    (new InstallerContractTest())->run($root);
    (new StagePipelineIntegrationTest())->run($root);
    (new ToolchainRepairerTest())->run();
    (new UpdateSecurityTest())->run();
    (new SelfUpdaterTest())->run($root);
    (new ToolchainUpdateTest())->run($root);
    (new DoctorTest())->run($root);
    (new ProfileDetectorTest())->run();
    (new ToolchainLockTest())->run($root);
    (new TypePhpPatchManifestTest())->run($root);
    (new UnifiedPatchApplierTest())->run();
    (new ReproducibilityInputTest())->run($root);
    (new WindowsReplayContractTest())->run($root);
    (new ElfStaticVerifierTest())->run();
    fwrite(STDOUT, "[PASS] repository structure is independent and self-contained\n");
    fwrite(STDOUT, "[PASS] global launcher uses the private user layout without a project plugin\n");
    fwrite(STDOUT, "[PASS] installers are user-private, digest-locked, and package-manager-free\n");
    fwrite(STDOUT, "[PASS] CLI stages emit stable exits, logs, and diagnostic bundles\n");
    fwrite(STDOUT, "[PASS] doctor repair promotes only verified toolchain generations\n");
    fwrite(STDOUT, "[PASS] update manifests and downloads fail closed on tampering or interruption\n");
    fwrite(STDOUT, "[PASS] CLI updates self-check, activate atomically, reject unsafe ZIPs, and roll back\n");
    fwrite(STDOUT, "[PASS] toolchain updates verify signed locks, preserve failures, and roll back\n");
    fwrite(STDOUT, "[PASS] doctor is read-only and detects healthy, missing, and corrupt inputs\n");
    fwrite(STDOUT, "[PASS] project profiles combine Composer locks and structure and fail closed on conflicts\n");
    fwrite(STDOUT, "[PASS] toolchain lock schema and digest guards are valid\n");
    fwrite(STDOUT, "[PASS] TypePHP patch manifest and patch set are guarded\n");
    fwrite(STDOUT, "[PASS] unified patches apply exactly and fail closed on drift\n");
    fwrite(STDOUT, "[PASS] normalized reproducibility input is deterministic\n");
    fwrite(STDOUT, "[PASS] Windows replay remains CLI-only and lock-driven\n");
    fwrite(STDOUT, "[PASS] ELF static verifier rejects interpreter-bearing artifacts\n");
    exit(0);
} catch (Throwable $throwable) {
    fwrite(STDERR, '[FAIL] ' . $throwable->getMessage() . PHP_EOL);
    exit(1);
}
